version: "3.9"

services:

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: device_management
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend_api
    ports:
      - "5238:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_web
    ports:
      - "5173:5173"
    depends_on:
      - backend