// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AllocationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tb");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_nv");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("lich_su_cap_phat");
                });

            modelBuilder.Entity("backend.Models.Depreciation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_kh");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("gia_tri_con_lai");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tb");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phuong_phap_tinh");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("khau_hao");
                });

            modelBuilder.Entity("backend.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tb");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ten_thiet_bi");

                    b.Property<decimal?>("OriginalCost")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("nguyen_gia");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_mua");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("loai");

                    b.HasKey("Id");

                    b.ToTable("thiet_bi");
                });

            modelBuilder.Entity("backend.Models.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_yc");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_gui");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("loai_yeu_cau");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai_duyet");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_nv");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("yeu_cau");
                });

            modelBuilder.Entity("backend.Models.RequestDevice", b =>
                {
                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_yc");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tb");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong");

                    b.HasKey("RequestId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("yeu_cau_thiet_bi");
                });

            modelBuilder.Entity("backend.Models.ReturnHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_th");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tinh_trang");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tb");

                    b.Property<DateTime>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_thu_hoi");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_nv");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("lich_su_thu_hoi");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_nv");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vai_tro");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("nhan_vien");
                });

            modelBuilder.Entity("backend.Models.AllocationHistory", b =>
                {
                    b.HasOne("backend.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Depreciation", b =>
                {
                    b.HasOne("backend.Models.Device", "Device")
                        .WithOne("Depreciation")
                        .HasForeignKey("backend.Models.Depreciation", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("backend.Models.Request", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.RequestDevice", b =>
                {
                    b.HasOne("backend.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Request", "Request")
                        .WithMany("RequestDevices")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backend.Models.ReturnHistory", b =>
                {
                    b.HasOne("backend.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Device", b =>
                {
                    b.Navigation("Depreciation");
                });

            modelBuilder.Entity("backend.Models.Request", b =>
                {
                    b.Navigation("RequestDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
